services:
  server:
    container_name: upload-server
    build: .
    restart: unless-stopped
    volumes:
      - upload-server-log:/usr/src/app/logs
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /usr/src/app/uploads:size=${TMPFS_SIZE:-2G}
    environment:
      - ID_LENGTH
      - MAX_FILE_SIZE
      - MAX_CONVERTIBLE_IMAGE_SIZE
      - FILE_EXPIRES
      - TRUST_PROXY
      - DIRECTORY=/usr/src/app/uploads
      - LOG_DIRECTORY=/usr/src/app/logs
    ports:
      - ${PORT:-80}:80

volumes:
  upload-server-log:
