services:
  server:
    container_name: upload-server
    build: .
    restart: unless-stopped
    volumes:
      - upload-server-data:/usr/src/app/data
      - upload-server-log:/usr/src/app/logs
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /usr/src/app/uploads:size=${TMPFS_SIZE:-2G}
    environment:
      - ID_CHARS
      - ID_LENGTH
      - FILE_EXPIRY
      - PUBLIC_MAX_FILE_SIZE=${MAX_FILE_SIZE:-}
      - PUBLIC_MAX_CONVERTIBLE_IMAGE_SIZE=${MAX_CONVERTIBLE_IMAGE_SIZE:-}
      - ADDRESS_HEADER=${TRUST_PROXY:+X-Forwarded-For}
      - XFF_DEPTH=${TRUST_PROXY:-}
      - ORIGIN
    ports:
      - ${PORT:-80}:3000

volumes:
  upload-server-data:
  upload-server-log: